export const MAKE_REQUEST="MAKE_REQUEST"
export const SUCCESS_REQUEST="SUCCESS_REQUEST"
export const FAIL_REQUEST="FAIL_REQUEST"

export const OPEN_POPUP="OPEN_POPUP"
export const ADD_SUCCESS="ADD_SUCCESS"

export const UPDATE_SUCCESS="UPDATE_SUCCESS"
export const DELETE_SUCCESS="DELETE_SUCCESS"

export const REQ_GETBYCODE_SUCC="REQ_GETBYCODE_SUCC"